services:
  postgres:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: suredriver
      POSTGRES_PASSWORD: suredriver
      POSTGRES_DB: suredriver
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
